// AUTOCOMPLETE FUNCTION

function autocomplete(inp, arr) {
    var currentFocus;
    inp.addEventListener("input", function (e) {
        var a, b, i, val = this.value;
        closeAllLists();
        if (!val) { return false; }
        currentFocus = -1;
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        this.parentNode.appendChild(a);
        for (i = 0; i < arr.length; i++) {
            if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                b = document.createElement("DIV");
                b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                b.innerHTML += arr[i].substr(val.length);
                b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
                b.addEventListener("click", function (e) {
                    inp.value = this.getElementsByTagName("input")[0].value;
                    closeAllLists();
                });
                a.appendChild(b);
            }
        }
    });
    inp.addEventListener("keydown", function (e) {
        var x = document.getElementById(this.id + "autocomplete-list");
        if (x) x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
            currentFocus++;
            addActive(x);
        } else if (e.keyCode == 38) {
            currentFocus--;
            addActive(x);
        } else if (e.keyCode == 13) {
            e.preventDefault();
            if (currentFocus > -1) {
                if (x) x[currentFocus].click();
            }
        }
    });
    function addActive(x) {
        if (!x) return false;
        removeActive(x);
        if (currentFocus >= x.length) currentFocus = 0;
        if (currentFocus < 0) currentFocus = (x.length - 1);
        x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
        for (var i = 0; i < x.length; i++) {
            x[i].classList.remove("autocomplete-active");
        }
    }
    function closeAllLists(elmnt) {
        var x = document.getElementsByClassName("autocomplete-items");
        for (var i = 0; i < x.length; i++) {
            if (elmnt != x[i] && elmnt != inp) {
                x[i].parentNode.removeChild(x[i]);
            }
        }
    }
    document.addEventListener("click", function (e) {
        closeAllLists(e.target);
    });
}
var facultyNamesList = ["Srimathi  R",
    "Sreedevi V T",
    "Hemamalini",
    "Gnana Swathika O V",
    "Sasipriya P",
    "Kanimozhi G",
    "Febin Daya J L",
    "Nithya Venkatesan",
    "Meenakshi J",
    "Sri Revathi B",
    "Senthil Kumar N",
    "Lavanya V",
    "Meera P S",
    "Sri Ramalakshmi P",
    "Anantha Krishnan V",
    "Prabhakar M",
    "Angeline Ezhilarasi G",
    "Lenin N C",
    "Chendur Kumaran R",
    "Peer Fathima A",
    "Balamurugan P",
    "Nilanjan Tewari",
    "Jamuna K",
    "Subbulekshmi D",
    "Angalaeswari S",
    "Deepa T",
    "Iyswarya Annapoorani K",
    "Kuruseelan S",
    "Vaithilingam C",
    "Binu Ben Jose D R",
    "Umayal C",
    "Gunabalan R",
    "Premalatha L",
    "Mohamed Imran A",
    "Arul R",
    "Jayapragash R",
    "Sumathi  V",
    "Inayathullah Abdul Kareem",
    "Hari Krishnan  K",
    "Joseph Jeya Anand  S",
    "Reeves Wesley J",
    "Deepa  Damodaran",
    "Sudarsanam S K",
    "Venkatesh R",
    "Sharon Sophia",
    "Saju B",
    "Aruna R",
    "Balaji J",
    "Anuradha A",
    "Gopinathan N",
    "Raja Rajeswari  G",
    "Vaidhyanatha Balaji K V",
    "S Saleem",
    "Sumathi G N",
    "Thangaraja Arumugam",
    "J Bhavani",
    "Nisha R",
    "Asi Vasu Deva Reddy",
    "Shwetha M Krishnappa",
    "L R K Krishnan",
    "S Divya",
    "Malay Bhattacharjee",
    "Biswabhusan Bhuyan",
    "Buvanesh",
    "Jyotirmayee Satapathy",
    "Mekhala Antony",
    "Subhamitra Patra",
    "Meenakshi Sankaran",
    "Praveen Kakada",
    "Sudheer Muhammed K M",
    "Muhammed Shafi M K",
    "Chitra Dey",
    "Sujatha Manohar",
    "Mahalakshmi S",
    "John Kennedy  L",
    "Atanu Dutta",
    "Kalyani Desikan",
    "Kaliyappan M",
    "Mini Ghosh",
    "Prabhakar V",
    "Muthunagai",
    "Vinitha G",
    "Rajendra Kumar K",
    "Tanushree Choudhry",
    "Vanchinathan P",
    "Manikandan N",
    "Saroj Kumar Dash",
    "Caroline Ponraj",
    "Jaganathan B",
    "Mohana N",
    "Uma Maheswari S",
    "Hannah Grace G",
    "Punithavelan N",
    "Radha S",
    "Pankaj Shukla",
    "Berin Greeni A",
    "Dhanasekar S",
    "Srutha Keerthi B",
    "Gopinath Mudhana",
    "Krishnendu Biswas",
    "Sanjit Das",
    "Navamathavan R",
    "Saravanakumar R",
    "David Maxim Gururaj A",
    "Abhishek Kumar Singh",
    "Fateh Veer Singh",
    "Revathi G K",
    "Jayanta Parui",
    "Nathiya N",
    "Parthiban V",
    "Manivannan A",
    "Santosh G",
    "Balamurugan B J",
    "Balamurali M M",
    "Devi Yamini S",
    "Poulomi De",
    "Vidhya V",
    "Felix.A",
    "Jayagopal R",
    "Milind Shrinivas Dangate",
    "Sangeetha P",
    "M. Dhivya",
    "Kiran Kumar Tadi",
    "Buthanapalli Ramakrishna",
    "Ilaiyaraja Perumal",
    "Sudip Debnath",
    "P Durgaprasad",
    "Pravinkashyap Kambhatla",
    "Somnath Bera",
    "B Ajitha",
    "Vigneshwaran Swaminathan",
    "P Vijay Kumar",
    "Satyanarayana Kumar Mallavarapu",
    "Eithiraj R D",
    "Ganesan Pandian",
    "G Ramachandran",
    "Sujoy Sarkar",
    "David Raj Micheal",
    "Durga Nagarajan",
    "Kalyan Banerjee",
    "Kutubuddin Ansari",
    "Manigandla Prasannalakshmi",
    "Balaji S",
    "Arockiasamy S",
    "RAJASEKARAKUMAR VADAPOO",
    "B. Krishna Kumar",
    "Rajivganthi C",
    "Harshavarthini Shanmugam",
    "M C Ramkumar",
    "Sowndarrajan P T",
    "Ravi Kumar Biroju",
    "Selva Chandrasekaran",
    "Nilesh A Wadibhasme",
    "Saradha Rajkumar",
    "Savariah Xavier Y C",
    "Bhuvaneswari G",
    "Govindarajan P",
    "Bhuvaneswari R",
    "Rajitha K",
    "Luke Gerard Christie",
    "Alan G",
    "Maya Rathnasabapathy",
    "Ajit I",
    "Alamelu C",
    "Rajasekaran V",
    "Vijayalakshmi Venkataraman",
    "Patchainayagi S",
    "Sivakami B",
    "Rashmi Rekha Borah",
    "Tiwari Mahalaxmi Shivkumar",
    "Vijayalakshmi V",
    "Sibaram Badatya",
    "Pooja Raghav",
    "Binu Sahayam D",
    "Manali Karmakar",
    "Swati Sharma",
    "Akaitab Mukherjee",
    "Devi Meenakshi K",
    "Chithra G.K.",
    "Urjani Chakravarty",
    "Vineeth Radhakrishnan",
    "Divya Muraleedharan",
    "Vijayalakshmi Balachander",
    "Annamalai K",
    "Arockia Selvakumar",
    "Bhaskara Rao L",
    "Christo Michael T",
    "Davidson Jebaseelan",
    "Deivanathan R",
    "Devaprakasam D",
    "Elango M",
    "Feroskhan M",
    "Giridharan A",
    "Gobinath N",
    "Harish R",
    "Jafferson J M",
    "Janardhan Reddy  K",
    "Jegadeeshwaran R",
    "Jeyanthi S",
    "Joseph Daniel",
    "Karunamurthy K",
    "Lakshmi Pathi Jakkamputi",
    "Lenin Babu  M C",
    "Manavalla Sreekanth",
    "Manimaran R",
    "Mohan R",
    "Narayanan R",
    "R. Padmanabhan",
    "Radha R",
    "Raghukiran Nadimpalli",
    "Sakthivel G",
    "Saravanakumar D",
    "Sasikumar M",
    "Senthil Kumar M",
    "Shyam Kumar M B",
    "Siva Kumar R",
    "Sivarajan S",
    "Sreekanth Dondapati",
    "Sridhar V G",
    "Sugumaran V",
    "Tamil Selvan P",
    "Venkatachalam G",
    "Venugopal T",
    "Vinayagamurthy G",
    "Bhisham Kumar Dhurandher",
    "Manoj Kumar R",
    "Gajanand Gupta",
    "Mrutyunjay Panigrahi",
    "Muralimohan",
    "Swagatika Mohanty",
    "Ayub Ahmed Janvekar",
    "Tapan Kumar Mahanta",
    "Awani Bhushan",
    "Anjali Gopakumar",
    "Arun Kumar A",
    "Elavenil S",
    "Helen Santhi M",
    "Karthikeyan K",
    "Karthiyaini S",
    "Mohan K",
    "Ramesh Kannan M",
    "Sabumon P C",
    "Saravanan K",
    "Senthilpandian M",
    "Shanmugasundaram",
    "Vasugi K",
    "Vasugi V",
    "Yamini Sreevalli I",
    "Goutham Sarang",
    "T Palani Rajan",
    "N Gayathri",
    "Vinusowndarya",
    "M Maanvizhi",
    "Georgy Sunny",
    "Jesica Roshima A",
    "Selvakumar",
    "Vasanth Kumar",
    "Deepika SG",
    "Bhuvaneshwari Mohan",
    "Abraham Sudharson Ponraj",
    "Ananiah Durai S",
    "Anita Angeline A",
    "Anith Nelleri",
    "Annis Fathima A",
    "Augusta Sophy Beulet P",
    "Bala Murugan M S",
    "Berlin Hency V",
    "Bindu B",
    "Brintha Therese  A",
    "Chandrasekaran N",
    "Chitra K",
    "Gargi Raina",
    "Guga Priya G",
    "Hemanth C",
    "Jagannath M",
    "Jaya Vignesh T",
    "John Sahaya Rani Alex",
    "Kanchana Bhaaskaran V S",
    "Karthik R",
    "Kaustab Ghosh",
    "Lakshmi B",
    "Manikandan P",
    "Manoj Kumar R",
    "Menaka R",
    "Mohanaprasad  K",
    "Muthulakshmi S",
    "Nagajayanthi B",
    "Niraj Kumar",
    "Prakash V",
    "Prathiba A",
    "Ralph Samuel Thangaraj",
    "Ramesh R",
    "Ravi Prakash Dwivedi",
    "Ravi Sankar A",
    "Ravi V",
    "Reena Monica P",
    "Revathi S",
    "Sakthivel S M",
    "Sangeetha R G",
    "Saranya Nair M",
    "Sekar Sathya Narayanan",
    "Sivasubramanian A",
    "Sofana Reka S",
    "Srivatsan K",
    "Subhashini N",
    "Suchetha M",
    "Suganthi K",
    "Susan Elias",
    "Thiripurasundari D",
    "Umadevi S",
    "Usha Kiran Kommuri",
    "Velmathi G",
    "Vetrivelan P",
    "Vigneswaran T",
    "Vijayakumar P",
    "Vydeki D",
    "Vijayarajan R",
    "Om Prakash Sahu",
    "Arivarasi A",
    "Gayathri Sivakumar",
    "Papanasam E.",
    "Sathya Sree J",
    "Lucky Agarwal",
    "B Prashanth Kumar",
    "Pradeep Narayanan.S",
    "Ashish Kumar",
    "Chanthini Baskar",
    "S.Sivakumar",
    "E.Manikandan",
    "S. Selvendran",
    "Florence Gnana Poovathy J",
    "Jeetashree Aparajeeta",
    "Kalaivanan K",
    "P.Nirmala",
    "S.Shoba",
    "Sindhuja. M",
    "A.Bharathi Sankar",
    "Idayachandran .G",
    "Ranjeet Kumar",
    "Saurav Gupta",
    "Richards Joe Stanislaus",
    "V.R Balaji",
    "Sasithradevi. A",
    "Henridass.A",
    "E.Sathish",
    "Soundara Pandian M S",
    "Sankar D",
    "Prema E",
    "Rabbiraj C",
    "Rajavenkatesan P R L",
    "Kesavamoorthy R",
    "Ambika R Nair",
    "Ganesan K",
    "M.S.Sharmila",
    "Jayendra Kasture",
    "Jishnu J R",
    "Anandha Krishna Raj S",
    "Tania Sebastian",
    "Rajasathya K R",
    "K Kamban Socretes",
    "Shinsa P Mathew",
    "T Abul Hassan",
    "Ankit Kumar Padhy",
    "Anbarasi G",
    "Zakkariya T H",
    "Navami",
    "Arun D Raj",
    "Dulung Sengupta",
    "Shanthi Krishna",
    "Aswathy Sukumaran",
    "Vijaya Bharathi Ravikumar",
    "Marasakatla Madhavi",
    "Karthik Shiva",
    "Ramya S R",
    "Sivagami M",
    "Pradeep Kumar  T.S",
    "Nisha  V.M",
    "Nithya Darisini  P.S",
    "Sajidha S A",
    "Sathis Kumar B",
    "Jeganathan L",
    "Maheswari R",
    "Vergin Raja Sarobin M",
    "Rukmani P",
    "Harini S",
    "Maheswari N",
    "Nayeemulla Khan",
    "Pattabiraman V",
    "Graceline Jasmine S",
    "Thomas Abraham J V",
    "Appalaraju Muralidhar",
    "Ilakiyaselvan N",
    "Sathyarajasekaran K",
    "Parvathi R",
    "Ummity Srinivasa Rao",
    "Saleena B",
    "Khadar Nawas K",
    "Prakash B",
    "Maheswari S",
    "Rajesh Kanna B",
    "Shridevi S",
    "Vijayalakshmi A",
    "B V A N S S Prabhakar Rao",
    "Premalatha M",
    "Bharathi Raja S",
    "Viswanathan V",
    "Rajkumar S",
    "Malathi G",
    "Kumar R",
    "Priyaadharshini M",
    "Kanchana Devi V",
    "Kavya Alluru",
    "Jayaram B",
    "Nivedita M",
    "Bharadwaja Kumar",
    "Jayasudha M",
    "Ganesan R",
    "Jenila Livingston L M",
    "Rekha D",
    "Rajesh Kumar",
    "Umamaheswari E",
    "Rajarajeswari S",
    "Neela Narayanan V",
    "ADMNul Quadir Md",
    "Christy Jackson J",
    "Tulasi Prasad Sariki",
    "Alok Chauhan",
    "Rabindra Kumar Singh",
    "Syed Ibrahim S P",
    "Ramesh Ragala",
    "Nachiyappan S",
    "Pradeep K V",
    "Sivabalakrishnan M",
    "Gayathri R",
    "Punitha K",
    "Rajesh M",
    "Rajiv Vincent",
    "Anusooya G",
    "Sandhya P",
    "Hema N",
    "Prassanna J",
    "Priyadarshini J",
    "Prabakaran R",
    "Shola Usha Rani",
    "Karmel A",
    "Suganya G",
    "Sridhar R",
    "Asha S",
    "Nithyanandam P",
    "Subbulakshmi T",
    "Renta Chintala Bhargavi",
    "Geetha S",
    "Asnath Victy Phamila Y",
    "Janaki Meena M",
    "Jagadeesh Kannan R",
    "Sweetlin Hemalatha C",
    "Nagaraj S V",
    "Rajalakshmi R",
    "Ganapathy S",
    "Renuka Devi S",
    "Shyamala L",
    "Jayanthi R",
    "Anusha K",
    "Jani Anbarasi L",
    "Prasad M",
    "Amit Kumar Tyagi",
    "Braveen M",
    "Muthumanikandan V",
    "Ilavarasi A. K",
    "Ayesha SK",
    "Kirthica S",
    "Radhika Selvamani B",
    "Bhuvaneswari A",
    "Manas Ranjan Prusty",
    "Jothi R",
    "Balasundaram A",
    "Muthukumaran K",
    "Venkatraman S",
    "Edward Jero S",
    "Ashoka Rajan R",
    "Jayalakshmi S L",
    "Menaka Pushpa A",
    "Pavithra L K",
    "Parkavi K",
    "Shivani Gupta",
    "Vani V",
    "Mirza Galib Anwarul Husain Baig",
    "Anita X",
    "Subbulakshmi P",
    "Amrit Pal",
    "Leninisha S",
    "Bhanu Chander Balusa",
    "Swaminathan A",
    "Rishikeshan C. A.",
    "Sandeep Kumar Satapathy",
    "Richa",
    "Sindhia Lingaswamy",
    "Vedhapriyavadhana R",
    "Arun Kumar Sivaraman",
    "Ganala Santoshi",
    "Sakthivel V",
    "Seshu Babu Pulagara",
    "Prakash P",
    "Cinu C Kiliroor",
    "Vijayakumar K P",
    "Pradeep K",
    "Radha R",
    "Kalaipriyan T",
    "Rajakumar Arul",
    "Sudha A",
    "Suganeshwari G",
    "Shruti Mishra",
    "P. Valarmathi",
    "Bhuvaneswari Amma N.G.",
    "Abishi Chowdhury",
    "A. Sheik ADMNullah",
    "Priyadarshini Ramasubramanian",
    "Manimegalai T",
    "Indra Priyadharshini S",
    "D. Kavitha",
    "M. Suguna",
    "A. Sherly Alphonse",
    "Abinaya S"
]
var schoolNamesList = ["SELECT", "SCOPE", "VITSOL", "SENSE", "VFIT", "SCE", "SMEC", "SSL", "SAS", "VITBS"];

autocomplete(document.getElementById("get-faculty-name"), facultyNamesList);
autocomplete(document.getElementById("get-school-name"), schoolNamesList);


// GET INPUT

// const facultyValue =""

// function getFaculty(){
//     const faculty = document.getElementById("get-faculty-name");
//     facultyValue = faculty.value;
//     ShowFacultyName(facultyValue)
// }

// function ShowFacultyName(facultyValue){
//     document.getElementById("faculty-name").innerHTML=facultyValue;
// }

// TABLE

function getTable(){
    let table = document.getElementById('cabin-table');
    facultyNamesList.forEach(faculty => {
        var row = table.insertRow();
        var cell1 = row.insertCell();
        var cell2 = row.insertCell();
        var cell3 = row.insertCell();
        var cell4 = row.insertCell();
        cell1.innerHTML = faculty;
        cell2.innerHTML = "<img src=\"pic.webp\">";
        cell3.innerHTML = "AB3-101";
        cell4.innerHTML = "9999999999";
    });
}

getTable();